server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://bloggydb.cc47xdveec3n.ap-south-1.rds.amazonaws.com
    username: postgres
    password: rootPassword
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
