server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bloggy_db
    username: postgres
    password: rootPassword
    driver-class-name: org.postgresql.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
